### ISSUE TITLE
onSelect not caller for all selected cells

### ISSUE THREAD

**Issue by IgnacioHR** [DarkRiDDeR/js-table-cell-selector#1]
Hello,

I've noticed the onSelect event function that can be indicated in the configuration is not called for all selected cells but just for the cells where the mouse is travelling over.

In order to test this problem I added a console.log(...) to display information about the cell selected. Then, start a selection with the mouse and monitor the console. If you select a rectangular area of 3x3 you should see the onSelect is not called 9 times but just the times a new "unselected" cell was added to the selection.

**Comment by DarkRiDDeR** [comment]
Hi, yes, this is a bug. It is necessary to correct it and add a flag that would show the previous state of the selected cells. As there will be time, I will do it. I think that this will not take much time. Also, if you urgently need, then do it yourself and add pull request

**Comment by IgnacioHR** [comment]
Hello Thanks for acknowledging it and the fast response.

I actually implemented a workaround that consist of managing the selection at the onFinishSelect event.

It is not as efficient as wen updating the selection while the mouse is moving but works for me now. I'll be happy to wait for the final fix.

I also want to ask for an improvement that you might consider that is adding an event and some logic to handle "unselection" events. for example, If you are using the mouse and press button on cell [0,0] and extends selection to cell [4,4] a box of 5x5 is selected (row and col starts from 0) and highlighted (mouse button is not released yet!). Now, if you move to cell [3,3] and constraint selection to a box of 4x4 the "border" (that consist of cells [n,4] and [4,n]) should be signaled as unselected via unselected event or similar.

Thanks!

**Comment by DarkRiDDeR** [comment]
I made changes to the correct logic. The npm repository has not updated yet. Take bundle from here https://github.com/DarkRiDDeR/js-table-cell-selector/tree/master/dist

**Comment by DarkRiDDeR** [comment]
can be downloaded from npm the repository
