### ISSUE TITLE
Incorrect number of columns when colspan is present

### ISSUE THREAD

**Issue by IgnacioHR** [DarkRiDDeR/js-table-cell-selector#4]
Hello,

I just wanted to report a bug that hit me today on this line of the code.

[selector.js#L157](https://github.com/DarkRiDDeR/js-table-cell-selector/blob/ffa44ee7f91223735fb75edfe634039ca613b5ec/src/selector.js#L157)

Imagine a table like this (simplified example)
```html
<table>
  <tbody>
    <tr>
      <td>
        <p>&nbsp;</p>
      </td>
      <td colspan="8">
        <p>Bla Bla Bla</p>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <p>&nbsp;</p>
      </td>
      <td>
        <p>xxx</p>
      </td>
      <td>
        <p>yyy</p>
      </td>
      <td>
        <p>zzz</p>
      </td>
      <td>
        <p>aaa</p>
      </td>
      <td>
        <p>bbb</p>
      </td>
      <td>
        <p>ccc</p>
      </td>
      <td>
        <p>ddd</p>
      </td>
    </tr>
  </tbody>
</table>
```

After the number of columns is calculated using the `length` of the nodes. the matrix is initialized with 8 columns.
Later, the loop that considers the colspan value from the node in lines 192 to 205 encounters that the table contains 9 columns so it reach the catch exception.

I'm afraid I can't provide a fix to the code because in my project I migrated the code to Typescript and a lot of things are different, so I'm going to paste my typescript code here and modify directly to try to match the javascript code:

```ts
        for (let row of rows) {
            const colElem = getElementsByTagNames("td, th", row);
            const rowCols = colElem.reduce((pre,curr) => pre + (<HTMLTableCellElement>curr).colSpan,0);
            if (rowCols > this.countCols) {
                this._countCols = rowCols;
            }
        }
```

I hope this can help others as well.

Regards and thank you for sharing this beautiful code!

**Comment by DarkRiDDeR** [comment]
Thank you! I have fixed this error.
