### ISSUE TITLE
Processing rowspan

### ISSUE THREAD

**Issue by IgnacioHR** [DarkRiDDeR/js-table-cell-selector#5]
Hi,

I fixed another issue on a test table with rowspan > 1 at some rows. I fixed two small issues:

1) Calculating the matrix rows when rowspan is present
``` typescript
    initSizeMatrix () {
        const rows = this.table.getElementsByTagName("tr");
        this._countCols = 0;
        this._countRows = 0;
        for (let rowIdx = 0; rowIdx < rows.length; rowIdx++) {
            const row = rows.item(rowIdx);
            const colElem = getElementsByTagNames("td, th", row);
            const rowCols = colElem.reduce((pre,curr) => pre + (<HTMLTableCellElement>curr).colSpan,0);
            if (rowCols > this.countCols) {
                this._countCols = rowCols;
            }
            this._countRows += colElem.reduce((pre,curr) => Math.max((<HTMLTableCellElement>curr).rowSpan, pre), 0);
        }

        this.matrix = new Array<Array<Array<number>>>(this._countRows);
```
2) crestFn changes the value of ix and this is the source of array out of bounds errors
``` typescript
            const crestFn = () => {
                let _ix = ix;
                while (_ix < this.countCols && rowCrest[_ix]) {
                    rowCrest[_ix]--;
                    this.matrix[iy][_ix][0] = this.matrix[iy-1][_ix][0] || 0 - 1;
                    this.matrix[iy][_ix][1] = this.matrix[iy-1][_ix][1];
                    _ix++;
                }
            };
```

I'm confident #1 is right, but how the information is stored in the matrix is a complex algorithm and I've no time to fully understand it so I'm 85% confidence the fix #2 is right just because it works and it does not cause more array index out of bound exceptions but I've not been able to fully test the getCell function is returning the right cell when rowSpan > 2 in all cells in a row.

Best!
Ignacio

**Comment by DarkRiDDeR** [comment]
Most likely your problems were related to incorrect processing of lines in my code. This is not due to incorrect calculation of the size matrix. I fixed that and it should now work correctly. 

See https://stackoverflow.com/questions/11742946/get-the-number-of-rows-in-a-html-table

See new version 0.6 and commit 6eaab36e70fc72674d82b536e9f09d11145f957f
