### ISSUE TITLE
ignorde Cell is selectable

### ISSUE THREAD

**Issue by Dreknor** [DarkRiDDeR/js-table-cell-selector#6]
ignoreThead -option is set to true, but the cells are selectable (same as in demo)

**Comment by DarkRiDDeR** [comment]
Hi, I made some changes, look fix issue #6 "ignore Cell is selectable". I have not updated the version in NPM yet, I plan to make some more changes first.

**Comment by DarkRiDDeR** [comment]
see new version 0.6
